name: Windows compilation

on:
  push:
    branches: master

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install QT
      run: choco install qt-sdk-windows-x64-mingw_opengl_seh
    - name: Call qmake
      run: qmake fhex.pro
    - name: make
      run: make
    - uses: actions/upload-artifact@v1
      with:
        name: fhex-master
        path: .
