name: Windows compilation

on:
  push:
    branches: master

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install QT
      uses: jurplel/install-qt-action@v2
    - name: Install MinGW 7.3
      run: choco install mingw --version 7.3.0
      # We use 7.3.0 since it's the supported one: https://doc.qt.io/qt-5/windows.html
    - name: Call qmake
      run: qmake fhex.pro
    - name: make
      run: make
    - uses: actions/upload-artifact@v1
      with:
        name: fhex-master
        path: .
